[package]
name = "underflow-chad"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.11.0"
dotenv = "0.15.0"
lazy_static = "1.5.0"
serde_json = "1.0.140"
supabase_rs = "0.4.2"
tera = "1.20.0"
